---
title: "checkData"
author: "Jesse"
date: "19/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(casebase)
library(doParallel)
```


```{r echo=TRUE, include=FALSE, warning=FALSE}


#alldiseases<-c("LAML","ACC","BLCA","LGG","BRCA","CESC","CHOL","LCML","COAD","CNTL","ESCA","FPPP","GBM","HNSC","KICH","KIRC","KIRP","LIHC","LUAD","LUSC","DLBC","MESO","MISC","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THYM","THCA","UCS","UCEC","UVM")

diseases<-c("ACC","BLCA","LGG","BRCA","CESC","CHOL","COAD","ESCA","GBM","HNSC","KICH","KIRC","KIRP","LIHC","LUAD","LUSC","DLBC","MESO","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THYM","THCA","UCS","UCEC","UVM")

registerDoParallel(2)
useableDisease=""
maxCoef=NA
for(i in 1:length(diseases)){

currentDisease=diseases[i]
currentData <- readRDS(paste("Data/data",currentDisease,".Rds",sep=""))$merged.dat

#remove rows with NA
highDimSurvData=na.omit(currentData)
highDimSurvData <- highDimSurvData[highDimSurvData$OS >= 0, ]
sam=sample(nrow(highDimSurvData),nrow(highDimSurvData)-1 )
partHighDimSurvData=highDimSurvData[sam, ]
y=as.matrix(partHighDimSurvData[,c(2,3)])
x=as.matrix(partHighDimSurvData[,c(4:length(highDimSurvData[1,]))])
new_data=as.data.frame(t(x[-c(sam), ]))
glmnetElasticFit=fitSmoothHazard.fit(x,y,time="OS",event="status",family=c("glmnet"),ratio=10,parallel=TRUE,nfold=10,alpha=0.5)

if(max(coef(glmnetElasticFit))>0){
useableDisease=c(useableDisease,currentDisease)
maxCoef=c(maxCoef,max(coef(glmnetElasticFit)))
}
print(currentDisease)
}


useableDisease
maxCoef
```

```{r warning=FALSE}
currentDisease="LGG"
currentData <- readRDS(paste("Data/data",currentDisease,".Rds",sep=""))$merged.dat

#remove rows with NA
highDimSurvData=na.omit(currentData)
highDimSurvData <- highDimSurvData[highDimSurvData$OS >= 0, ]
sam=sample(nrow(highDimSurvData),nrow(highDimSurvData)-1 )
partHighDimSurvData=highDimSurvData[sam, ]
y=as.matrix(partHighDimSurvData[,c(2,3)])
x=as.matrix(partHighDimSurvData[,c(4:length(highDimSurvData[1,]))])
new_data=as.data.frame(t(x[-c(sam), ]))
registerDoParallel(3)
glmnetElasticFit=fitSmoothHazard.fit(x,y,time="OS",event="status",family=c("glmnet"),ratio=10,parallel=TRUE,nfold=10,alpha=0.5)
abGlmnetElasticFit=absoluteRisk(glmnetElasticFit,time = seq(0,10000, 1000),newdata = new_data)
plot(abGlmnetElasticFit,type='l',col="black",lwd=2)

```
